import { useState } from 'react';

const MOCK_MARKDOWN = `# Content Calendar — Mock Channel

**Quality Score:** 8.4/10

---

## Channel Analysis

Channel performs best with structured tutorial formats under 20 minutes. Audience skews toward working developers seeking practical copy-paste-ready solutions.

**Top Performing Patterns:**
- Step-by-step build tutorials (3x avg retention, high CTR)
- Error fix walkthroughs (low drop-off, high comments)

---

## Trend Analysis

| Topic | Type | Opportunity |
|-------|------|-------------|
| React Server Components | rising | 8.7/10 |
| TypeScript 5.x features | stable | 6.2/10 |
| Bun runtime benchmarks | rising | 7.9/10 |

---

## Video Concept 1 — React Server Components from scratch

**Title:** React Server Components in 15 Minutes (actually useful)

**Hook:** Most RSC tutorials show you the theory. This one shows you why your app is broken without them — and how to fix it in 15 minutes.

**Outline:**
- 0:00 Hook + problem statement
- 1:30 What RSC actually is (30 seconds)
- 2:00 Build: data-fetching component
- 7:00 Build: client island inside server tree
- 11:00 Performance comparison
- 14:00 Wrap-up + CTA

---

## Video Concept 2 — Bun vs Node.js — real benchmark

**Title:** Bun vs Node.js: I Ran 5 Real Benchmarks (Surprising Results)

**Hook:** Everyone is saying Bun is 3x faster than Node. I ran 5 actual benchmarks on a real app to see if that's true.

---

## Video Concept 3 — Migrating a JS codebase to TypeScript

**Title:** Migrate JavaScript to TypeScript Without Losing Your Mind

**Hook:** I've seen developers delay a TypeScript migration for 2 years because they thought it meant rewriting everything. You don't.

---

## Video Concept 4 — Full-stack app with Next.js App Router

**Title:** Full Stack Next.js App Router — Build & Deploy in 20 Minutes

**Hook:** The App Router changed how you think about full-stack Next.js. This is the full picture — from empty folder to deployed app — in 20 minutes.

---

*Generated by AutoContent*
`;

interface Props {
  calendarId: string;
}

export function MarkdownExportButton({ calendarId }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleExport() {
    setLoading(true);
    setError(null);
    try {
      const text =
        calendarId === 'mock'
          ? MOCK_MARKDOWN
          : await fetch(`/api/content-calendars/${calendarId}/markdown`, { credentials: 'include' }).then((res) => {
              if (!res.ok) throw new Error(`Export failed: ${res.status}`);
              return res.text();
            });
      const blob = new Blob([text], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `calendar-${calendarId}.md`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={handleExport}
        disabled={loading}
        className="inline-flex items-center gap-2 px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {loading ? 'Exporting…' : 'Export Markdown'}
      </button>
      {error && <p className="text-sm text-red-600">{error}</p>}
    </div>
  );
}
