import { useState } from 'react';

const MOCK_PDF_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Content Calendar — Mock Channel</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 24px; color: #111; line-height: 1.7; }
    h1 { font-size: 28px; border-bottom: 2px solid #111; padding-bottom: 8px; }
    h2 { font-size: 20px; margin-top: 32px; color: #1a1a1a; }
    h3 { font-size: 16px; color: #333; margin-top: 24px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
    th { background: #f5f5f5; font-weight: bold; }
    .score { display: inline-block; background: #111; color: #fff; padding: 2px 10px; border-radius: 4px; font-size: 14px; }
    .concept { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-top: 24px; }
    footer { margin-top: 48px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>Content Calendar — Mock Channel</h1>
  <p><span class="score">Quality Score: 8.4 / 10</span></p>

  <h2>Channel Analysis</h2>
  <p>Channel performs best with structured tutorial formats under 20 minutes. Audience skews toward working developers seeking practical, copy-paste-ready solutions.</p>
  <h3>Top Performing Patterns</h3>
  <ul>
    <li>Step-by-step build tutorials — 3x avg retention, high CTR</li>
    <li>Error fix walkthroughs — low drop-off, high comments</li>
  </ul>

  <h2>Trend Analysis</h2>
  <table>
    <thead><tr><th>Topic</th><th>Type</th><th>Opportunity</th></tr></thead>
    <tbody>
      <tr><td>React Server Components</td><td>Rising</td><td>8.7 / 10</td></tr>
      <tr><td>TypeScript 5.x features</td><td>Stable</td><td>6.2 / 10</td></tr>
      <tr><td>Bun runtime benchmarks</td><td>Rising</td><td>7.9 / 10</td></tr>
    </tbody>
  </table>

  <h2>Video Concepts</h2>

  <div class="concept">
    <h3>1 — React Server Components from Scratch</h3>
    <p><strong>Title:</strong> React Server Components in 15 Minutes (actually useful)</p>
    <p><strong>Hook:</strong> Most RSC tutorials show you the theory. This one shows you why your app is broken without them — and how to fix it in 15 minutes.</p>
    <p><strong>Outline:</strong> 0:00 Hook · 1:30 What RSC actually is · 2:00 Build data-fetching component · 7:00 Client island · 11:00 Performance comparison · 14:00 Wrap-up</p>
  </div>

  <div class="concept">
    <h3>2 — Bun vs Node.js Real Benchmark</h3>
    <p><strong>Title:</strong> Bun vs Node.js: I Ran 5 Real Benchmarks (Surprising Results)</p>
    <p><strong>Hook:</strong> Everyone is saying Bun is 3x faster than Node. I ran 5 actual benchmarks on a real app to see if that's true.</p>
    <p><strong>Outline:</strong> 0:00 Hook · 1:00 Setup · 3:00 Benchmarks 1–3 · 8:00 Benchmarks 4–5 · 12:00 Should you switch? · 14:30 Wrap-up</p>
  </div>

  <div class="concept">
    <h3>3 — Migrate JS to TypeScript Without Losing Your Mind</h3>
    <p><strong>Title:</strong> Migrate JavaScript to TypeScript Without Losing Your Mind</p>
    <p><strong>Hook:</strong> I've seen developers delay a TypeScript migration for 2 years because they thought it meant rewriting everything. You don't.</p>
    <p><strong>Outline:</strong> 0:00 The migration myth · 1:30 tsconfig + allowJs · 4:00 Rename files · 9:00 Strict mode · 12:00 Gotchas · 14:30 Wrap-up</p>
  </div>

  <div class="concept">
    <h3>4 — Full Stack Next.js App Router</h3>
    <p><strong>Title:</strong> Full Stack Next.js App Router — Build &amp; Deploy in 20 Minutes</p>
    <p><strong>Hook:</strong> The App Router changed how you think about full-stack Next.js. From empty folder to deployed app in 20 minutes.</p>
    <p><strong>Outline:</strong> 0:00 What we're building · 1:00 Setup · 3:00 Data layer · 8:00 UI + Server Actions · 15:00 Deploy · 19:00 Wrap-up</p>
  </div>

  <footer>Generated by AutoContent (mock preview)</footer>
</body>
</html>`;

interface Props {
  calendarId: string;
}

export function PdfExportButton({ calendarId }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleExport() {
    setLoading(true);
    setError(null);
    try {
      let blob: Blob;
      if (calendarId === 'mock') {
        blob = new Blob([MOCK_PDF_HTML], { type: 'text/html' });
      } else {
        const res = await fetch(`/api/content-calendars/${calendarId}/pdf`, { credentials: 'include' });
        if (!res.ok) throw new Error(`PDF export failed: ${res.status}`);
        blob = await res.blob();
      }
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = calendarId === 'mock' ? `calendar-${calendarId}.html` : `calendar-${calendarId}.pdf`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 100);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'PDF export failed');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={handleExport}
        disabled={loading}
        className="inline-flex items-center gap-2 px-4 py-2 bg-red-700 text-white text-sm font-medium rounded-lg hover:bg-red-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {loading ? 'Generating PDF…' : 'Export PDF'}
      </button>
      {error && <p className="text-sm text-red-600">{error}</p>}
    </div>
  );
}
